import type { Metadata } from 'next';

// These styles apply to every route in the application
import './globals.css';
import DesktopUi from './DesktopUi';

export const metadata: Metadata = {
  title: 'Campingping',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen justify-center items-center">
          <DesktopUi />
          <div className="w-full md:max-w-[450px] h-full flex justify-center overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
