export const regions = [
  { fullRegionName: '서울특별시', shortRegionName: '서울시' },
  { fullRegionName: '부산광역시', shortRegionName: '부산시' },
  { fullRegionName: '대구광역시', shortRegionName: '대구시' },
  { fullRegionName: '인천광역시', shortRegionName: '인천시' },
  { fullRegionName: '광주광역시', shortRegionName: '광주시' },
  { fullRegionName: '대전광역시', shortRegionName: '대전시' },
  { fullRegionName: '울산광역시', shortRegionName: '울산시' },
  { fullRegionName: '세종특별자치시', shortRegionName: '세종시' },
  { fullRegionName: '경기도', shortRegionName: '경기도' },
  { fullRegionName: '강원도', shortRegionName: '강원도' },
  { fullRegionName: '충청북도', shortRegionName: '충청북도' },
  { fullRegionName: '충청남도', shortRegionName: '충청남도' },
  { fullRegionName: '전라북도', shortRegionName: '전라북도' },
  { fullRegionName: '전라남도', shortRegionName: '전라남도' },
  { fullRegionName: '경상북도', shortRegionName: '경상북도' },
  { fullRegionName: '경상남도', shortRegionName: '경상남도' },
  { fullRegionName: '제주특별자치도', shortRegionName: '제주도' },
];
